security:
   basic:
     enabled: true

management:
      security:
          enabled: true

logging:
   level:
     io:
       pivotal: DEBUG


greeting:
    displayFortune: false

quoteService: http://quote-service-dev.cfapps.io/quote
